modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
[[mods]]
modId="weirdworld"
version="${file.jarVersion}"
displayName="Weird World"
logoFile="weirdworld.png"
credits="Just me for now"
authors="reetling"
description='''
A mod that adds fantasy biome variants.
'''

[[dependencies.weirdworld]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.weirdworld]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
